model_list:
  - model_name: gpt-4o-mini
    litellm_params:
      model: gpt-4o-mini
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-4o
    litellm_params:
      model: gpt-4o
      api_key: os.environ/OPENAI_API_KEY
  - model_name: openai/gpt-4o-mini
    litellm_params:
      model: gpt-4o-mini
      api_key: os.environ/OPENAI_API_KEY
  - model_name: anthropic/claude-3-5-sonnet-20240620
    litellm_params:
      model: claude-3-5-sonnet-20240620
      api_key: os.environ/ANTHROPIC_API_KEY
  - model_name: anthropic/claude-3-5-haiku-20241022
    litellm_params:
      model: claude-3-5-haiku-20241022
      api_key: os.environ/ANTHROPIC_API_KEY
  - model_name: gemini/gemini-1.5-flash
    litellm_params:
      model: gemini-1.5-flash
      api_key: os.environ/GEMINI_API_KEY
  - model_name: gemini/gemini-1.5-pro
    litellm_params:
      model: gemini-1.5-pro
      api_key: os.environ/GEMINI_API_KEY
